name: Node App

on:
  push:
    branches:
      - main

jobs:
  testnodeapplication:

    #runs-on: ubuntu-latest
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run build 
        docker-compose up -d
      
    
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
      
    - name: Lint Dockerfile
      uses: brpaz/hadolint-action@master
      with:
          dockerfile: ./Dockerfile
        
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: sagark24/nodeapplication:v1
  
  
  
  
         
      
    

